[build]
  command = "yarn build"
  publish = "dist"
  

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
#redirecciones del backend
[[redirects]]
  from = "/"
  to = "https://backend-del-tata.contenidx.workers.dev/"
  status = 200