[build]
  command = "yarn build"
  publish = "dist"
  

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
#redirecciones del backend
[[redirects]]
  from = "/upload"
  to = "https://backend-del-tata.contenidx.workers.dev/upload"
  status = 200
  [[redirects]]
  from = "/process-form"
  to = "https://backend-del-tata.contenidx.workers.dev/process-form"
  status = 200
  [[redirects]]
  from = "/get-access-token"
  to = "https://backend-del-tata.contenidx.workers.dev/get-access-token"
  status = 200